# app.yaml defines how app is run such as handling requests for app deployment for app engine
runtime: nodejs24 #latest version - tells which runtine env to use. Ensures env where Node.js is installed
service: default #specifies which service the configuration runs on, default = main service for the project

# defines routing (how app eng serves files when users visit URLs). Tells how to handle incoming HTTP requests
handlers:
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|map)) # matching any request with files ending with these
    static_files: www/\1 # \1 references the first capture group which means it maps directly to the requested file name.
    upload: www/.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|map) # which files to include when uploading to app eng

  # any requests to /assets serves files from www/assets (serves directory intead of individual files)
  - url: /assets
    static_dir: www/assets

  # Serve all other files and URLs through index.html (lets Angular handle the
  # routing because app eng doesn't know all the URLs for example when user visits route /booking app eng doesn't know what file that corresponds to)
  - url: /.*
    static_files: www/index.html
    upload: www/index.html

# app is running in production environment inside NodeJs runtime, tells libraries (Angular, Ionic, Firebase, etc...) to run in production mode
env_variables:
  NODE_ENV: "production"
